### ISSUE TITLE
How do images work in this repo?

### ISSUE THREAD

**Issue by Overload119** [shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh#5]
```
Warning: Prop `src` did not match. Server: "/Users/amirsharif/Projects/sendapostcardonline/public/packsmedia/images/letter-599b40cf9aba6c364ac2bfb054d291d7.png" Client: "/packs/media/images/letter-599b40cf9aba6c364ac2bfb054d291d7.png"
    in img (created by CompleteAddressForm)
    in div (created by CompleteAddressForm)
    in div (created by CompleteAddressForm)
    in CompleteAddressForm (created by Connect(CompleteAddressForm))
    in Connect(CompleteAddressForm)
    in Provider
    in Unknown
```

I'm getting this error. 
Where is packsmedia coming from?
Why the disconnect between client and server? 

(I am using almost all the same files as this repo)

// assets.js (loader)
```
const { env, publicPath } = require('../configuration.js')

module.exports = {
  test: /\.(jpg|jpeg|png|gif|svg|eot|ttf|woff|woff2)$/i,
  use: [{
    loader: 'file-loader',
    options: {
      publicPath,
      name: env.NODE_ENV === 'production' ? '[name]-[hash].[ext]' : '[name].[ext]'
    }
  }]
}
```

**Comment by Overload119** [comment]
Related: I replaced with a null-loader although I saw in this repo there's only a comment to do that.

https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/blob/master/config/webpack/serverWebpackConfiguration.js#L24

```
  serverWebpackConfig.module.rules.forEach(loader => {
    if (loader.use && loader.use.filter) {
      loader.use = loader.use.filter(
        item =>
          !(typeof item === 'string' && item.match(/mini-css-extract-plugin/)),
      );
    }
    if (loader.use && loader.use[0].loader === 'file-loader') {
      loader.use.loader = 'null-loader';
    }
  });
```

**Comment by justin808** [comment]
Yes. I want to make some improvements to this repo.

Take a look at this WIP: https://github.com/shakacode/react-webpack-rails-tutorial/pull/484

That should handle:

1. Images
2. CSS modules and sass-resources-loader

Contributions are invited!

and [Join me on slack with this invite](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE)!

**Comment by Overload119** [comment]
I don't understand how null-loader will help, since the strings on the server and client will always be different. 

I managed to resolve my issue by changing this line to publicPath instead of outputPath.
https://github.com/shakacode/react-webpack-rails-tutorial/pull/484/files#diff-0addedbb690e835a95c3b8cd67f1361cR55

**Comment by justin808** [comment]
@Overload119 I'm not sure what lines you're referring to:

Maybe here: https://github.com/shakacode/react-webpack-rails-tutorial/pull/484/files#diff-0addedbb690e835a95c3b8cd67f1361cR54-R55 ?

```
  serverWebpackConfig.output = {
    filename: 'server-bundle.js',
    globalObject: 'this',
    // If using the React on Rails Pro node server renderer, uncomment the next line
    // libraryTarget: 'commonjs2',
    path: config.outputPath,
    publicPath: config.outputPath
    // https://webpack.js.org/configuration/output/#outputglobalobject
  }
```
