### ISSUE TITLE
Need to update readme for HMR

### ISSUE THREAD

**Issue by traverspinkerton** [shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh#7]
I ran into an issue on step 8. HMR was not enabled by default in `webpacker.yml` for my dev server so when I tried to add fast refresh I was getting some strange errors.

I would add a note in Step 8 such as:
   - Note: Ensure HMR is enabled for the dev server. `hmr: true` in  `webpacker.yml`

**Comment by justin808** [comment]
Updated! Thanks!
